export default {
  services: [
    {
      title: 'A-2/Zoning Location Survey',
      header: 'zoning location survey',
      header2: 'zoning location survey in flood zone',
      slug: 'a-2-zoning-location-survey',
      img: '',
      text: `Commonly referred to as an “A-2” Survey. The term "A-2" is technically a standard of accuracy (all of our work here is of high A-2 standards), this survey is actually a Zoning Location Survey. This is the most common today, of all types of surveys that we perform, as it assists you in acquiring a building permit. It is a document required for such things as small additions to brand new houses and more. This survey, depicts your property and its improvements in regards to zoning matters. It gives you a look into your property from a standpoint of what potential you may have, any possibilities you may have for expansion and even possible subdivision questions can be answered. Though it generally depicts improvements to your property in regards to zoning matters, this is not to say that when we perform a Zoning Location Survey, that we cannot depict locations of fences, trees, specific items of interests, possible encroachments (by your neighbors or yourself), or anything that resides on your property that the town zoning department may have no interest in, but you may. Basically, you are getting a package of information regarding your residence and it’s position on your property, any other structures, their distances to your front, side & rear property lines, your coverage and or items specific to the town regulations. Most towns have a "Zoning Regulation Grid", a list of information that varies from town to town and zone to zone within your town. "Grids" are comprised of information that only a Land Surveyor is qualified to fill out. This allows the town to see what exactly your situation is on your property, before they can approve a permit for you to make alterations; additions, expansions, etc. This "Grid" (setbacks, square footage, coverage etc.) has 4 separate columns; Requirements, Existing Conditions, Proposed Conditions & "As-Built" Conditions. The "Final As-Built" is the final phase where the town gets to see all the information they need to see how ("As") your project was "Built". Once everything has been deemed acceptable in regards to zoning matters, you then get a Certificate of Occupancy  (C.O.) and the "Book is closed" on this project.`,
      text2: `Certain towns require additional information, for example; topography included in the A-2 Zoning Location Survey. This is additional elevation (vertical) information. See “Topographic Map”.`,
    },
    {
      title: 'Staking Property',
      header: 'Staking Survey',
      header2: '',
      slug: 'staking-property',
      img: '',
      text: `Most of a surveyors work in modern times is done on paper since most property lines in our area have already been established. Most people are surprised to find that a great majority of our time is spent in our office. That being said, there are certain needs that require that we physically "Stake Out" a piece of property, such as the installation of a fence, or if someone would like to do some clearing of trees or brush etc. Be it 1 single corner, a single line, a portion of a line, or an entire parcel, once we are mathematically "Tied In", we can stake anything. The method we commonly use to do this is the iron pins. There are times when a more substantial means is required and large concrete monuments can be installed. This is usually reserved for what we call "control", points that are inserted in the ground at major points on a map, such as Points of Curvature (P.C.) or angle points in the road. These are generally installed when Subdivisions are created. It is extremely rare that a home owner would install concrete monuments today, the iron pin is the common preferable method and will last far beyond your life time.While some surveyors still use wood stakes, the method we use to do this is with iron pins.`,
      text2: `Another staking service we provide is to stake (pin) concrete foundation footings for Contractors.`,
    },
    {
      title: 'Map Of Property',
      header: '',
      header2: '',
      slug: 'map-of-property',
      img: '',
      text: `When a situation arises that requires a different level of attention. A "Map of Property" may include zoning information, but it is generally a Survey that holds a higher standard in the area of physical location of improvements to your property and can include almost anything and everything that may affect it.`,
      text2: '',
    },
    {
      title: 'Topographic Survey Map',
      header: 'Topographic Survey Map',
      header2: '',
      slug: 'topographic-survey-map',
      img: '',
      text: `A Topographic map depicts vertical information, as opposed to horizontal information. This map will allow a designer to see the contour (grade) of the land, by drawing contour lines and or spot elevations. There are many different reasons for ordering a Topographic map, such as drainage, landscape issues, to design of retaining walls and all sorts of issues within the property that may effect your project.`,
      text2: '',
    },
    {
      title: 'Elevation Certificates',
      header: 'Elevation Certificates',
      header2: '',
      slug: 'elevation-certificates',
      img: '',
      text: `This 4 page document includes; elevation (vertical) information. Generally used for the purpose of acquiring flood insurance. The Elevation Certificate includes information; of your finished floor, basement, crawl space, garage, etc., in relation to your Flood Zone's Base Flood Elevation (BFE). It also includes photographs and even your "Mechanicals" (hot water heater, furnace, etc.). This 4 page document is a Federal Emergency Management Agency (FEMA) provided document. Other information (highest & lowest grade) for possible application for a Letter of Map Amendment (LOMA) is also provided`,
      text2: '',
    },
    {
      title: 'Outline Boundary',
      header: 'Outline Boundary',
      header2: '',
      slug: 'outline-boundary',
      img: '',
      text: `Though most parcels of land are mathematically mapped out and on file with the Town Clerk's office, not every parcel is. Some clients during our initial consultation have shown some surprise when they find out that the documents they need are not readily available at the town. Potential clients sometimes call us with the assumption that every property has a map down at the town, or that all property at some time has been physically staked, and they just want us to find them. Unfortunately this is not the case. Unless the former owner of your land, or your neighbors (adjoining property), has been "Staked Out", then more than likely you will not have any information in any form available to you. The Outline Boundary Survey is basically the Survey we perform when we are "Starting from scratch". We are literally outlining your boundary on paper. We Survey the perimeter of your Land and several parcels around you, to gather enough data to be able to establish your property lines. If your parcel is large enough, it can also have potential for Subdivision. This Document should, in turn, be filed for record in the Town Clerk's office for all time. Future Surveyor's will have to work off of this Map when surveying the lots around you.`,
      text2: '',
    },
  ],
  projects: [
    {
      title: '448 Pequot Avenue',
      address: '448 Pequot Avenue',
      city: 'Fairfield, CT',
      slug: 'pequot-avenue',
      projType: 'Proposed Conditions',
      img: '',
      text: `The aim of this project was to create a "Zoning Location Survey" for some major renovation to an old house from 1834. Brian St. Pierre, a local Contractor that also hires us frequently, was in charge of this project.`,
      highlight: true,
      project: 'Southport Expansion',
      client: 'Kathy Mc.Hugh',
    },
    {
      title: '16 Orland Street',
      address: '16 Orland Street',
      city: 'Milford, CT',
      slug: 'orlando-street',
      projType: 'Existing Conditions',
      img: '',
      text: `The aim of the project was to create a "Zoning Location Survey" of existing conditions for Don & Susan so they can look at options for their garage. It is old, and had an old fashioned wood type floor, that cannot hold the weight of a car of today.`,
      highlight: true,
      project: 'Addressing The Garage',
      client: 'Donald & Susan Persett',
    },
    {
      title: '116 Rowland Road',
      address: '116 Rowland Road',
      city: 'Fairfield, CT',
      slug: 'rowland-road',
      projType: 'Proposed Conditions',
      img: '',
      text: `The aim of this project was to create a "Zoning Location Survey" for proposal, for Luis & Mary Pat. As you can see, down by the beach, some towns require a great amount of detail on plans. They really do like to protect these areas as best they can.`,
      highlight: true,
      project: 'A Small Addition',
      client: 'Luis & Mary Pat Garate',
    },
    {
      title: '15 Point Beach Drive',
      address: '15 Point Beach Drive',
      city: 'Milford, CT',
      slug: '',
      projType: 'Elevation Certificate',
      img: '',
      text: `The aim of the project was to create an updated Elevation Certificate for Jimmie. He was selling this property, and before he puts it on the market he wanted to get a new certificate that reflected the FEMA Flood Zone Changes of July of 2013. This updated document will arm any perspective buyer with exactly what they need to get an accurate quote on Flood Insurance, before they put in a Bid on this amazing home on the water's edge. Jimmie, who owns The famous "Jimmie's Restaurant" in West Haven, CT since 1925, is quite an entertaining fellow; but we are still waiting for some clams one day for lunch (maybe he is reading this!).`,
      highlight: false,
      project: 'The Elevation Certificate',
      client: 'Jimmie',
    },
    {
      title: '110 Waterbury Avenue',
      address: '110 Waterbury Avenue',
      city: 'Milford, CT',
      slug: '',
      projType: 'As-Built',
      img: '',
      text: `The aim of this project was to create a "Zoning Location Survey" for proposal. Bill's intentions were to lift his house up on concrete pillars, and also acquire a new elevation certificate for his insurance company. His finished floor is now about 5 feet above his Base Flood Elevation of 15!. FEMA updated their maps in the middle of this project, so it was advanageous that his house was raised as high as it was. Bill went from being in Flood Zone AE(10) to VE(15) by the time he was complete 2 years later.`,
      highlight: false,
      project: 'Raising the roof, or in this case, the whole house!',
      client: 'Walter William Ehri',
    },
    {
      title: '137 Ryegate Terrace',
      address: '137 Ryegate Terrace',
      city: 'Stratford, CT',
      slug: '',
      projType: 'Zoning Location Survey',
      img: '',
      text: `Though we do many Surveys in Flood Zones, down by the beach, and very large projects both commercial and residential, many of our surveys are for simple addtions such as we did here for Joe & Jill. We actually pride ourselves on handling these sorts of small jobs. We understand that no matter how small a job is, it is never actually "small" to the owner!, it is always a huge undertaking when it is "your" property and "your" project. We treat everyone exactly the same here, and no one gets any more or less attention, no matter how "big" or "small" your project is. We go to great lengths to try and make everyone feel comfortable and especially confident, that we are looking out for their best interests.`,
      highlight: false,
      project: 'Lordship Addition',
      client: 'Ryan & Jennifer Wagner',
    },
    {
      title: '1564 Melville Avenue',
      address: '1564 Melville Avenue',
      city: 'Fairfield, CT',
      slug: '',
      projType: 'Proposed Conditions',
      img: '',
      text: `The aim of this project was to create a "Zoning Location Survay" for Tom to add a simple addition in the rear. Tom is a local contractor/builder in Fairfield for 30 years that we work with quite a bit. We share a great work relationship with many contractors like Tom. We understand that we work closely with your client, and you are trusting us to represent you when you hire with us. The best part is knowing that they feel confident going with us for their project time and time again. It's especially nice to know that Tom used us recently for a project on his own personal property. Thanks Tom!`,
      highlight: false,
      project: 'Small Rear Addition',
      client: 'Tom & Janet Wrabel',
    },
  ],
};